<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Yepages JS</title>
        <link rel="preconnect" href="https://fonts.googleapis.com/%22%3E">
        <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
        <link href='https://fonts.googleapis.com/css?family=Special Elite' rel='stylesheet'>
        <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
        <link rel="stylesheet" href="assets/styles/css/style.css" />
    </head>
<body id="register">
<form action="index.php?route=register" method="post">
    <fieldset>
  <label for="firstName">Username</label>
  <input type="text" id="registerUsername" name="registerUsername">
    </fieldset>
 
    <fieldset>
  <label for="email">Email</label>
  <input type="email" id="registerEmail" name="registerEmail">
    </fieldset>
    <fieldset>
  <label for="password">Mot de passe</label>
  <input type="password" id="registerPassword" name="registerPassword">
    </fieldset>
    <fieldset>
  <label for="confirmPassword">Confirmation du mot de passe</label>
  <input type="password" id="registerConfirmPwd" name="registerConfirmPwd">
    </fieldset>
  <input type="hidden" name="formName" value="register">

  <input id=button type="submit" value="Créer un compte">
</form>

</body>

</html>