<form action="index.php" method="post">
    <fieldset>
  <label for="firstName">Prénom</label>
  <input type="text" id="firstName" name="firstName">
    </fieldset>
    <fieldset>
  <label for="lastName">Nom</label>
  <input type="text" id="lastName" name="lastName">
    </fieldset>
    <fieldset>
  <label for="email">Email</label>
  <input type="email" id="email" name="email">
    </fieldset>
    <fieldset>
  <label for="password">Mot de passe</label>
  <input type="password" id="password" name="password">
    </fieldset>
    <fieldset>
  <label for="confirmPassword">Confirmation du mot de passe</label>
  <input type="password" id="confirmPwd" name="confirmPwd">
    </fieldset>
  <input type="hidden" name="formName" value="register">

  <input type="submit" value="Créer un compte">
</form>