<form action="index.php" method="post">
  <h1>Connexion</h1>
  <fieldset>
  <label for="login">Email</label>
  <input type="email" id="login" name="login">
  </fieldset>
  <fieldset>
  <label for="password">Mot de passe</label>
  <input type="password" id="password" name="password">
  </fieldset>
  <input type="hidden" name="formName" value="login">
  <input id="button" type="submit" value="Se connecter">
  <p>Pour s'incrire cliquez <a href ="https://victoroustiakine.sites.3wa.io/res03-php-projetDistortion/index.php?route=register">ICI</a> </p>
</form>
