

<aside>
                <nav>
                    <h1>Navigation</h1>
                    
                <?php  
    // var_dump($data);
                        $truc = $data[0];
                        foreach($truc as $category){
                            
                          
                          
                          
                                $salons =  $category->getSalon(); 
                                echo "<h2>".$category->getTitle()."</h1>";
                            echo "<ul>";
                            
                            // echo "</br>";
                            
                            foreach($salons as  $salon){
                                
                                // array_push($tabSalon,$salon->getTitle());
                                  
                                echo "<li class = hidden >...".$salon->getTitle()."</li>";
                                
                                // echo "</br>";
                              
                               
                            }
                            echo "</ul>";
                        }
                        
                        ?>
                                           
                                           
                 
                </nav>
</aside>