

<aside>
                <nav>
                    <h1>Navigation</h1>
                    
                <?php  
    // var_dump($data);
                        $truc = $data[0];
                        foreach($truc as $category){
                            
                                $salons =  $category->getSalon(); 
                                echo "<h2>".$category->getTitle()."</h1>";
                            echo "<ul>";
                            
                            foreach($salons as  $salon){
                                  
                                echo "<li class = hidden ><a href =index.php?route=".$salon->getId().">...".$salon->getTitle()."</a></li>";
          
                            }
                            echo "</ul>";
                        }
                        
                        ?>
                                           
                                           
                 
                </nav>
</aside>