<!--<<<<<<<<< saved version-->
<main>
    <section>
        <?php
        
        $newData = $data["leBonSalon"][0]->getPost();
        
        foreach($newData as $post){
            
            // echo $post->getContent();
            // echo "<br>";
            // var_dump( $post);
            echo $post->getContent();
            echo "<br>";
            echo "<br>";
        }
    // var_dump($newData);
    // for($i = 0 ; $i <count( $newData);$i++){
        
        
    //     echo $newData[0];
    // }
        
        ?>
    </section>
    <section>
        <label for="message">Texte</label>
        <textarea id="story" name="story"
          rows="5" cols="33">
        
        </textarea>
        <button type="submit">Envoyer</button>
    </section>
         
        
        </textarea>
        <button type="submit">Envoyer</button>
    </section>
</main>
<!--=========
<section>
<form>
<label for="message">Texte</label>
<textarea name ="message" id="message">
    
</textarea>

<button type="submit">Envoyer</button>
</form>
</section>
>>>>>>>>> local version-->