<!--<<<<<<<<< saved version-->
<main>
    <section>
        <?php
        
        ?>
    </section>
    <section>
        <label for="message">Texte</label>
        <textarea id="story" name="story"
          rows="5" cols="33">
        
        </textarea>
        <button type="submit">Envoyer</button>
    </section>
          rows="5" cols="33">
        
        </textarea>
        <button type="submit">Envoyer</button>
    </section>
</main>
<!--=========
<section>
<form>
<label for="message">Texte</label>
<textarea name ="message" id="message">
    
</textarea>

<button type="submit">Envoyer</button>
</form>
</section>
>>>>>>>>> local version-->