<main>
    <section>
        <?php
        // var_dump($data[1]);
        $salonss = $data[1];
        foreach($salonss as $salon){
            
            // var_dump($salon);
        }
        ?>
    </section>
    <section>
        <label for="message">Texte</label>
        <textarea id="story" name="story"
          rows="5" cols="33">
        
        </textarea>
        <button type="submit">Envoyer</button>
    </section>
</main>